#!/bin/bash
set -e
set -o pipefail

third_component=$(ifconfig | sed -n 's/.*192\.168\.\([0-9]\+\)\..*/\1/p')

[[ "$third_component" =~ [0-9]+ ]] || {
  echo 1>&2 "error: invalid third component of IP address ($third_component)."
  exit 1
}

echo "scanning 192.168.$third_component.*:"
echo "--------------------------------------------------------------"

{
  echo "host ip name status"
  echo "------- ---------------- ----------------------------- -------"
  nmap -oG - -sP "192.168.$third_component.0/24" | grep -v '^#'
} | awk '{print $2, $3, $4, $5, $6}' | column -t 

exit $?

# The below alternative will tell nmap to output in XML, then
# will use the xmltodict module to parse the XML and convert it
# to a python dictionary, then will pretty-print the result. If
# you want to run this, apt install python-xmltodict.
xmltodict='
import xmltodict, pprint, json, sys
pp = pprint.PrettyPrinter(indent=4)
print json.dumps( xmltodict.parse( sys.stdin.read() ), indent=4 )
'

nmap -oX - -sP "192.168.$third_component.0/24" | python -c "$xmltodict"
