#!/bin/bash
# This  script  will  find all hpp or cpp files under the current
# folder and will then enter into  a polling loop waiting for any
# of  them  to change. As soon as one changes then a make command
# will be run with a target if one has been specified.

bash_script="
    /usr/bin/make "$@"
    echo '-----------------------------------------------------------'
"

find . \( -name "*.?pp" -or -name "*.c" \) | entr -c /bin/bash -c "$bash_script"
