#!/bin/bash
# Get the IP address on this system.
ip a | grep -E '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' -o \
     | sort -u                                                     \
     | grep -v '127.0.0.1'                                         \
     | grep -v '\.255$'
