#!/bin/bash
# Show a list of wifi networks with dmenu and connect to the se-
# lected one, or escape to cancel.
set -e
set -o pipefail

dmenu=~/dev/suckless/dmenu/latest/dmenu

selection="$(nmcli dev wifi | $dmenu -l 30)"

[[ -z "$selection" ]] && exit 0
# remove leading '*' which is found on the currently selected network.
selection="${selection//\*}"

set -- $selection

[[ "$1" == IN-USE ]] && exit 0

bssid="$1"

[[ "$bssid" =~ [0-9A-Z:]+ ]] || exit 1

echo "connecting to: $bssid"

nmcli dev wifi connect $bssid