#!/bin/bash
# This  script  will  find all hpp or cpp files under the current
# folder and will then enter into  a polling loop waiting for any
# of  them  to change. As soon as one changes then a make command
# will be run.
bash_script='
    /usr/bin/make;
    echo "-----------------------------------------------------------"
'

where="${1-:src}"
find "$where" -name "*.?pp" | entr -c /bin/bash -c "$bash_script"
